#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Demo.Resource", IsApplication=true)]

namespace Demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int city_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int disanxian = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int doufu = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int guobaorou = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int jiaozi = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int slogan = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int splash_screen = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int splashscreen = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int yuxiangrousi = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070023
			public const int buttonend = 2131165219;
			
			// aapt resource value: 0x7f07000e
			public const int citylist = 2131165198;
			
			// aapt resource value: 0x7f07002f
			public const int content_frame = 2131165231;
			
			// aapt resource value: 0x7f07000c
			public const int day = 2131165196;
			
			// aapt resource value: 0x7f07002e
			public const int drawer_layout = 2131165230;
			
			// aapt resource value: 0x7f070025
			public const int everydaybutton2 = 2131165221;
			
			// aapt resource value: 0x7f070015
			public const int finishbutton = 2131165205;
			
			// aapt resource value: 0x7f070033
			public const int getnumber = 2131165235;
			
			// aapt resource value: 0x7f070034
			public const int getpassword = 2131165236;
			
			// aapt resource value: 0x7f070030
			public const int imageView1 = 2131165232;
			
			// aapt resource value: 0x7f070022
			public const int imageViewcai = 2131165218;
			
			// aapt resource value: 0x7f070032
			public const int left_drawer = 2131165234;
			
			// aapt resource value: 0x7f07002c
			public const int linearLayout1 = 2131165228;
			
			// aapt resource value: 0x7f07002b
			public const int loginenter = 2131165227;
			
			// aapt resource value: 0x7f070005
			public const int manbutton = 2131165189;
			
			// aapt resource value: 0x7f070027
			public const int minebutton4 = 2131165223;
			
			// aapt resource value: 0x7f07000a
			public const int month = 2131165194;
			
			// aapt resource value: 0x7f070010
			public const int nextbutton = 2131165200;
			
			// aapt resource value: 0x7f070029
			public const int number = 2131165225;
			
			// aapt resource value: 0x7f070035
			public const int ok = 2131165237;
			
			// aapt resource value: 0x7f07002a
			public const int password = 2131165226;
			
			// aapt resource value: 0x7f070026
			public const int planbutton3 = 2131165222;
			
			// aapt resource value: 0x7f070020
			public const int radioButtonhun = 2131165216;
			
			// aapt resource value: 0x7f070019
			public const int radioButtonqing = 2131165209;
			
			// aapt resource value: 0x7f070021
			public const int radioButtonsu = 2131165217;
			
			// aapt resource value: 0x7f07001b
			public const int radioButtonxue = 2131165211;
			
			// aapt resource value: 0x7f070018
			public const int radioButtonyin = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int radioButtonyu = 2131165210;
			
			// aapt resource value: 0x7f070017
			public const int radioGroup3 = 2131165207;
			
			// aapt resource value: 0x7f07001f
			public const int radioGrouphunsu = 2131165215;
			
			// aapt resource value: 0x7f07002d
			public const int register = 2131165229;
			
			// aapt resource value: 0x7f070003
			public const int sexGroup = 2131165187;
			
			// aapt resource value: 0x7f070031
			public const int sloganenter = 2131165233;
			
			// aapt resource value: 0x7f07001d
			public const int star = 2131165213;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f07000b
			public const int textView10 = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int textView11 = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int textView12 = 2131165199;
			
			// aapt resource value: 0x7f070001
			public const int textView2 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int textView3 = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int textView4 = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int textView6 = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int textView8 = 2131165191;
			
			// aapt resource value: 0x7f070013
			public const int textView9 = 2131165203;
			
			// aapt resource value: 0x7f07001e
			public const int textViewhunsu = 2131165214;
			
			// aapt resource value: 0x7f07001c
			public const int textViewshiliang = 2131165212;
			
			// aapt resource value: 0x7f070016
			public const int textViewwea = 2131165206;
			
			// aapt resource value: 0x7f070011
			public const int textmeat = 2131165201;
			
			// aapt resource value: 0x7f070014
			public const int textsea = 2131165204;
			
			// aapt resource value: 0x7f070012
			public const int textveg = 2131165202;
			
			// aapt resource value: 0x7f070024
			public const int todaybutton1 = 2131165220;
			
			// aapt resource value: 0x7f070028
			public const int txtName = 2131165224;
			
			// aapt resource value: 0x7f070004
			public const int womanbutton = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int year = 2131165192;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Choose = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Donteat = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Endlayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragmentcontent = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Registerlayout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int birthday = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int choosecity = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int city = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int day = 2130968584;
			
			// aapt resource value: 0x7f040011
			public const int hun = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int hunsu = 2130968592;
			
			// aapt resource value: 0x7f040003
			public const int man = 2130968579;
			
			// aapt resource value: 0x7f04000b
			public const int meat = 2130968587;
			
			// aapt resource value: 0x7f040007
			public const int month = 2130968583;
			
			// aapt resource value: 0x7f04000e
			public const int nowweather = 2130968590;
			
			// aapt resource value: 0x7f040001
			public const int person = 2130968577;
			
			// aapt resource value: 0x7f040014
			public const int qing = 2130968596;
			
			// aapt resource value: 0x7f04000c
			public const int seasoning = 2130968588;
			
			// aapt resource value: 0x7f040002
			public const int sex = 2130968578;
			
			// aapt resource value: 0x7f04000f
			public const int shiliang = 2130968591;
			
			// aapt resource value: 0x7f040012
			public const int su = 2130968594;
			
			// aapt resource value: 0x7f04000d
			public const int vegetable = 2130968589;
			
			// aapt resource value: 0x7f040004
			public const int woman = 2130968580;
			
			// aapt resource value: 0x7f040016
			public const int xue = 2130968598;
			
			// aapt resource value: 0x7f040006
			public const int year = 2130968582;
			
			// aapt resource value: 0x7f040013
			public const int yin = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int yu = 2130968597;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
